from odoo import models, fields, api, _
from odoo.exceptions import UserError
from datetime import date, timedelta


class BoardReport(models.Model):
    _name = 'board.report'
    _description = 'Board Report'
    _order = 'period_start desc'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    def _default_employee(self):
        employee = self.env['hr.employee'].search(
            [('user_id', '=', self.env.uid)], limit=1)
        return employee

    name = fields.Char(
        string='Report Name',
        required=True,
    )
    period_start = fields.Date(
        string='Period Start',
        required=True,
    )
    period_end = fields.Date(
        string='Period End',
        required=True,
    )
    generated_by = fields.Many2one(
        'hr.employee',
        string='Generated By',
        default=_default_employee,
        readonly=True,
    )
    generated_date = fields.Datetime(
        string='Generated Date',
        default=fields.Datetime.now,
        readonly=True,
    )
    state = fields.Selection([
        ('draft', 'Draft'),
        ('published', 'Published'),
    ], string='Status', default='draft', tracking=True,
       group_expand='_group_expand_states')
    metric_value_ids = fields.One2many(
        'board.metric.value',
        'report_id',
        string='Metric Values',
        copy=False,
    )
    notes = fields.Text(
        string='Executive Summary',
    )
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        default=lambda self: self.env.company,
        required=True,
    )

    def _group_expand_states(self, states, domain, order):
        return [key for key, _ in self._fields['state'].selection]

    @api.constrains('period_start', 'period_end')
    def _check_period(self):
        for rec in self:
            if rec.period_start and rec.period_end and rec.period_end < rec.period_start:
                raise UserError(_(
                    'Period end date cannot be before period start date.'))

    # ---- Calculation Engine ----

    def _get_previous_period(self):
        """Calculate previous period of same duration."""
        self.ensure_one()
        if not self.period_start or not self.period_end:
            return None, None
        delta = self.period_end - self.period_start
        prev_end = self.period_start - timedelta(days=1)
        prev_start = prev_end - delta
        return prev_start, prev_end

    def _get_working_days_in_period(self, period_start, period_end):
        """Count weekdays (Mon-Fri) in the period."""
        if isinstance(period_start, str):
            period_start = date.fromisoformat(period_start)
        if isinstance(period_end, str):
            period_end = date.fromisoformat(period_end)
        current = period_start
        count = 0
        while current <= period_end:
            if current.weekday() < 5:  # Mon=0, Fri=4
                count += 1
            current += timedelta(days=1)
        return count

    def _get_working_hours_in_period(self, period_start, period_end, hours_per_day=8):
        """Working hours = working days * hours per day."""
        return self._get_working_days_in_period(period_start, period_end) * hours_per_day

    # ---- Built-in Metric Calculation Methods ----
    # Each corresponds to a metric code and is called via board.metric._run_calculation()

    def _compute_headcount(self, period_start, period_end):
        """Count of active + probation employees."""
        count = self.env['hr.employee'].search_count([
            ('employment_status', 'in', ('active', 'probation')),
        ])
        return float(count)

    def _compute_employee_utilisation_rate(self, period_start, period_end):
        """Total timesheet hours / (headcount × working hours in period) × 100."""
        headcount = self._compute_headcount(period_start, period_end)
        working_hours = self._get_working_hours_in_period(period_start, period_end)
        if headcount == 0 or working_hours == 0:
            return 0.0

        # Sum submitted/completed timesheet hours in period
        self.env.cr.execute("""
            SELECT COALESCE(SUM(total_hours), 0)
            FROM timesheet_week
            WHERE state IN ('submitted', 'completed')
              AND week_start >= %s
              AND week_end <= %s
        """, (period_start, period_end))
        total_hours = self.env.cr.fetchone()[0]

        denominator = headcount * working_hours
        if denominator == 0:
            return 0.0
        return (total_hours / denominator) * 100.0

    def _compute_attrition_rate(self, period_start, period_end):
        """Employees terminated in period / avg headcount × 100."""
        # Count offboardings completed in period (by last_working_date)
        terminated_count = self.env['hr.offboarding'].search_count([
            ('state', '=', 'completed'),
            ('last_working_date', '>=', period_start),
            ('last_working_date', '<=', period_end),
        ])

        # Headcount
        start_count = self.env['hr.employee'].search_count([
            ('employment_status', 'in', ('active', 'probation')),
        ])
        if start_count == 0:
            return 0.0
        return (terminated_count / start_count) * 100.0

    def _compute_absenteeism_rate(self, period_start, period_end):
        """Leave days / working days × 100."""
        working_days = self._get_working_days_in_period(period_start, period_end)
        headcount = self._compute_headcount(period_start, period_end)
        if working_days == 0 or headcount == 0:
            return 0.0

        # Count leave days (holidays) in period
        try:
            self.env.cr.execute("""
                SELECT COALESCE(SUM(number_of_days), 0)
                FROM hr_leave
                WHERE state = 'validate'
                  AND date_from >= %s
                  AND date_to <= %s
            """, (period_start, period_end))
            leave_days = self.env.cr.fetchone()[0]
        except Exception:
            leave_days = 0.0

        total_possible_days = working_days * headcount
        if total_possible_days == 0:
            return 0.0
        return (leave_days / total_possible_days) * 100.0

    def _compute_billable_hours(self, period_start, period_end):
        """Sum of submitted/completed timesheet hours in period."""
        self.env.cr.execute("""
            SELECT COALESCE(SUM(total_hours), 0)
            FROM timesheet_week
            WHERE state IN ('submitted', 'completed')
              AND week_start >= %s
              AND week_end <= %s
        """, (period_start, period_end))
        return float(self.env.cr.fetchone()[0])

    def _compute_revenue_per_employee(self, period_start, period_end):
        """Total payroll / headcount."""
        headcount = self._compute_headcount(period_start, period_end)
        if headcount == 0:
            return 0.0

        # Sum net pay from payslips in period
        self.env.cr.execute("""
            SELECT COALESCE(SUM(net_pay), 0)
            FROM hr_payslip
            WHERE state IN ('confirmed', 'paid')
              AND period_start >= %s
              AND period_end <= %s
        """, (period_start, period_end))
        total_payroll = self.env.cr.fetchone()[0]
        return total_payroll / headcount

    def _compute_average_resolution_time(self, period_start, period_end):
        """Average days from open_date to resolution_date for HR issues resolved in period."""
        self.env.cr.execute("""
            SELECT COALESCE(
                AVG(resolution_date - date_reported), 0)
            FROM hr_issue
            WHERE state IN ('resolved', 'closed')
              AND resolution_date IS NOT NULL
              AND date_reported IS NOT NULL
              AND resolution_date >= %s
              AND resolution_date <= %s
        """, (period_start, period_end))
        return float(self.env.cr.fetchone()[0])

    def _compute_open_issues(self, period_start, period_end):
        """Count of non-closed HR issues."""
        count = self.env['hr.issue'].search_count([
            ('state', 'not in', ('closed', 'resolved')),
        ])
        return float(count)

    # ---- Report Generation ----

    def action_calculate_metrics(self):
        """Calculate all active metrics for this report and store values."""
        self.ensure_one()
        if not self.period_start or not self.period_end:
            raise UserError(_('Please set both period start and end dates.'))

        # Delete existing metric values
        self.metric_value_ids.unlink()

        # Get active metrics
        metrics = self.env['board.metric'].search([('is_active', '=', True)])
        if not metrics:
            raise UserError(_(
                'No active metrics found. Please configure metrics first.'))

        # Calculate previous period values for trend
        prev_start, prev_end = self._get_previous_period()
        previous_values = {}
        if prev_start and prev_end:
            prev_report = self.search([
                ('period_start', '=', prev_start),
                ('period_end', '=', prev_end),
                ('id', '!=', self.id),
            ], limit=1)
            if prev_report:
                for val in prev_report.metric_value_ids:
                    previous_values[val.metric_id.id] = val.value

        # Calculate each metric
        MetricValue = self.env['board.metric.value']
        errors = []
        for metric in metrics:
            try:
                with self.env.cr.savepoint():
                    value = metric._run_calculation(self)
            except Exception as e:
                value = 0.0
                errors.append(_(
                    'Error calculating metric "%(metric)s": %(error)s'
                ) % {'metric': metric.name, 'error': str(e)})
                continue

            prev_val = previous_values.get(metric.id, 0.0)

            # Determine trend
            if prev_val == 0:
                trend = 'stable'
            elif value > prev_val * 1.02:
                trend = 'up'
            elif value < prev_val * 0.98:
                trend = 'down'
            else:
                trend = 'stable'

            MetricValue.create({
                'report_id': self.id,
                'metric_id': metric.id,
                'value': value,
                'previous_value': prev_val,
                'trend': trend,
            })

        self.generated_date = fields.Datetime.now()
        msg = _('Metrics calculated for report "%s".') % self.name
        if errors:
            msg += '\n' + '\n'.join(errors)
        self.message_post(body=msg)
        return True

    def action_publish(self):
        """Publish the report."""
        for rec in self:
            if rec.state == 'published':
                continue
            if not rec.metric_value_ids:
                raise UserError(_(
                    'Cannot publish report "%s" without calculated metrics. '
                    'Please calculate metrics first.'
                ) % rec.name)
            rec.state = 'published'
            rec.message_post(body=_('Report published by %s.') % self.env.user.name)
        return True

    def action_reset_draft(self):
        """Reset report to draft."""
        for rec in self:
            if rec.state == 'draft':
                continue
            rec.state = 'draft'
            rec.message_post(body=_('Report reset to draft by %s.') % self.env.user.name)
        return True

    # ---- Snapshot (data warehouse) ----

    def action_save_snapshot(self):
        """Save current metric values as historical snapshots for trend reporting."""
        self.ensure_one()
        if not self.metric_value_ids:
            raise UserError(_(
                'Cannot snapshot report "%s" — no metrics calculated yet. '
                'Please calculate metrics first.'
            ) % self.name)

        Snapshot = self.env['board.snapshot']
        now = fields.Datetime.now()
        created = 0

        for mv in self.metric_value_ids:
            Snapshot.create({
                'metric_id': mv.metric_id.id,
                'report_id': self.id,
                'value': mv.value,
                'snapshot_date': now,
                'period_start': self.period_start,
                'period_end': self.period_end,
            })
            created += 1

        self.message_post(body=_(
            'Snapshot saved: %(count)d metrics captured for trend reporting.'
        ) % {'count': created})
        return True
